# Sponsor/reward
reward:
  enable: false
  QR_code:
    - img: 
      link:
      text: 微信
    - img: 
      link:
      text: 支付宝

# Avatar (头像)
avatar:
  img: https://s21.ax1x.com/2024/04/25/pkPVgr6.jpg
  effect: true

  # 主色调相关配置
mainTone:
  enable: true # true or false 文章是否启用获取图片主色调
  mode: api # cdn/api/both cdn模式为图片url+imageAve参数获取主色调，api模式为请求API获取主色调，both模式会先请求cdn参数，无法获取的情况下将请求API获取，可以在文章内配置main_color: '#3e5658'，使用十六进制颜色，则不会请求both/cdn/api获取主色调，而是直接使用配置的颜色
  # 项目地址：https://github.com/anzhiyu-c/img2color-go
  api: https://img2color-go.vercel.app/api?img= # mode为api时可填写
  cover_change: true # 整篇文章跟随cover修改主色调
